name: 'inventory_srv'
tags: ['inventory_srv']
mysql:
    host: '192.168.224.128'
    port: 3306
    db: 'myshop_inventory_srv'
    password: 'xuanyizhao'
    user: 'root'
consul:
    host: '192.168.224.128'
    port: 8500
